environment:
  name: uk-production
services:
- name: sava-cart
  version: "2.0"
  environment_variables:
    locale: UK
    base_path: /
    title: VisionExpress
- name: sava-order
  version: "0.x"
  environment_variables:
    elasticsearch_url: http://35.204.12.239:9200
    elasticsearch_index_name: basket-data
- name: sava-stock
  version: "0.x"
  environment_variables:
    elasticsearch_url: http://35.204.12.239:9200
    elasticsearch_search_index_name: basket-data
    elasticsearch_analytics_index_name: basket-analytics